### ISSUE TITLE
Collection of some ideas for backend code cleanup

### ISSUE THREAD

**Issue by fredreichbier** [privacyidea/privacyidea#1204]
In the following, I am just collecting some ideas for the code cleanup milestone :-) Doesn't mean we should implement all of them.
* [x] This will come naturally with Python 3, but: **string handling**. It should always be clear if we are handling actual unicode strings, or bytestrings. This may be a bit hard in some cases, e.g. passwords that are encrypted in the database: service account passwords for LDAP resolvers are actually unicode, but RADIUS secrets are actually bytestrings.
* [ ] We could improve **input handling**. We sometimes had problems in the lib layer where variables ended up having different types than expected, which worked most of the time (which is why the unit tests didn't catch it), but broke in some cases, e.g. #889, #1117. We could try validating and casting all values on the API level to the right types before passing them to the lib level.
* [ ] We could improve **post policies**. Almost all postpolicy functions first parse the ``response.data``, and later dump the updated data again. I can imagine that it could even benefit performance if the postpolicy functions all operate on Python dictionaries, and we dump the final response to JSON at the very end of the request.
* [ ] We could get rid of **finalizers**. I know I added them myself in #1168, but I don't like them that much :-) They do their job (i.e. cleaning up database connections), but they result in very confusing control flow. It would be nicer if all resolvers had a method ``.close()`` which is called at the end of every request and performs all cleanup work. Likewise for audit objects.
* [ ] We could improve **per-request caching**. e.g. the function ``get_tokens(serial=...)`` is called in many of prepolicy functions (because we need it for the policy matching), which currently results in one DB request per invocation. We could try to cache the "current token object" in each request to improve performance.
* [ ] Based on the discussion in #1266 we could add a **caching** functionality for **ldap-requests** either with some python package or implemented with a FIFO-structure.

**Comment by fredreichbier** [comment]
We could look into using something like [Bowler](https://pybowler.io/) for automated refactoring.

**Comment by cornelinux** [comment]
@fredreichbier Can you please split these ideas into different issues?

**Comment by fredreichbier** [comment]
I opened several new issues for the ideas above. Because I couldn't think of good issue labels for some of the issues, I created a new ``code-cleanup`` label. Hope that's ok :-)
Closing this.
