### ISSUE TITLE
Why do all UIs look the same? 

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1961]
In a setup with redundant machines, internal machines, external machines, or test machines there might be a lot of privacyIDEA UIs.

"Why do all UIs look the same?"

We could simply add the name of the PI-Node in a prominent place in the UI - given, the admin could look at the browser URL line, but who does this? And this line does not scale in contrast to the web site.

# Todos

* [x] Improve documentation of PI_CSS
* [x] Add webui policy with action=show_privacyidea_node" (Note: the policy can have a node-condition!)
* [x] Display the privacyIDEA node in the UI using ``get_privacyidea_node`` from privacyidea.lib.config.py.

**Comment by plettich** [comment]
Maybe centered in the footer, together with some color coding?
Or maybe a (configurable) extra header row?

**Comment by cornelinux** [comment]
I think a header would be more sensible, since it is directly visible, when the admin goes through his browser tabs. ...somewhere next to the logo.
Actually we have the privacyidea servername and node name from pi.cfg. We could show this next to the logo or underneath the logo. This is imho also helpful, because the admin sees the node name also in the audit log.

Maybe we should restrict this, so that only the admin sees this.

**Comment by laclaro** [comment]
We have to cases here:
1. A Dev setup where you have several nodes in sync behind a load balancer. Maybe you would like to know on which node you end up.
2. Several Environments (Development, Testing, Staging, Productive) and you would like to differentiate between those. Usually you have the samle PI_NODES variable defined in all environments.

Since you probably copy your policies while moving from Dev to Prod through your environments, I suggest to rely on pi.cfg parameters only:
Use a single WebUI policy `identify_node` to identify node and environment from the configuration in pi.cfg.

1. Introduce a configuration parameter PI_ENVIRONMENT
2. Create a WebUI policy `identify_node` or a similar system configuration setting. This setting would have 3 options:
   - text
   - color
   - text and color

The first option is easily to implement. We would just display the environment name and the node name in the Menu bar. 

The option to add color involves more changes. We would [derive a color from the given environment string](https://stackoverflow.com/questions/3426404/create-a-hexadecimal-colour-based-on-a-string-with-javascript) and use it to change the color of a couple elements via css. To not disturb the WebUI design too much, I would suggest to change the orange logged-in user button (only visible after login) and/or to add some colored shadow to the menu bar.
Actually, we would need three colors (base, darker and lighter) to replace the color gradients.

**Comment by cornelinux** [comment]
> Since you probably copy your policies while moving from Dev to Prod through your environments, I suggest to rely on pi.cfg parameters only

This is a very good point that is must not be synced in the database.

But it is already that easy - check this out, @laclaro:

Create a file ``/opt/privacyidea/lib/python3.6/site-packages/privacyidea/static/css/my.css`` with the content:

~~~~css
body {
    background-color: green;
}
~~~~

In pi.cfg add:

~~~~
PI_CSS = "/static/css/my.css"
~~~~

Restart and be happy. 
Maybe we simply add a bit more documentation.

**Comment by plettich** [comment]
we could also add CSS classes to strategic elements and let the user customize the elements.
Classes could be something like:
- `pi-custom-{{ user.role }}`
- `pi-custom-{{ node }}`

Elements could be:
- header
- footer
- background
- logout-button
