### ISSUE TITLE
New Tokentype: Indexed Secret (Challenge)

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1986]
There could be an additional token type that acts as a challenge response token for a certain knowledge - similar to the questionnaire token.

# Basic concept

## Basic idea

A certain "secret" information is contained as an attribute in the userstore and is read/mapped by the useridresolver.

**Note: Since this is a mapped user attribute this information would also visible to administrators!**

## Enrollment

When enrolling such a token, this secret is preset with the value from the user store. The user or administrator can overwrite this value! This secret value is then stored in the encrypted otpkey of the token.

An ``ENROLL`` policy defines, which is the attribute, that contains the secret value.

Alternatively, just like with the sms or email token an event handler can be defined to set this to be a dynamic value. This way the value is read dynamically from the user store each time an authentication occurs. (I.e. the user or admin can *not* change the value during enrollment)

For this, the ``tokenhandler`` will get a new option to fetch the secret dynamically.
The token will have a ``tokeninfo`` field ``dynamic_attribute``, that indicates, that the attribute should be fetched dynamically.

## Authentication

The token type uses this information to request certain positions from this secret string from the user.

* The requested positions are random positions, which could also be in a mixed order like: 1,6,2.
* The number of requested positions can be configured. For this we would have an ``AUTH`` policy.
  (Do we always want to use a fixed number of random positions, or could we also do like 3-6 positions?)
* The token either reads the secret information from the token (which was set during the enrollment) or reads the secret information dynamically from the user store (for this the ``ENROLL`` action ``attribute`` is used.).

Thus the challenge text could be:

"Please provide the position 1,6,2 from your secret attribute."

TBD:
* Should we allow to request recurring positions like: 2,3,3 -> **Yes**
* ~~if not: what should we do, if the length of the secret information is shorter than the number of requested positions? Authentication Failure?~~

**Comment by cornelinux** [comment]
In regards to "dynamic" there are two levels:

1. Should the "attribute" of the value be changeable - like "use the employee number" or "use the birthday". So should this attribute:
    a) be dynamically read from the token config or from policies?
    b) be read from the token config and then be stored in the token itself (the attribute, not the value!)

2. Should the *value" be read from the user source at enrollment time or should the value of the attribute be read dynamically from the user source.

If both levels are dynamically, there is no sense in maybe having more than one of such tokens.

**Comment by cornelinux** [comment]
Ideas for the naming originate from

* Shared Secret
* Indexed Secret
* Knowledge
* SecretIndex

**Comment by laclaro** [comment]
I think "Indexed Secret" describes best the token type.

**Comment by cornelinux** [comment]
# Todo List

* [ ] implement basic functionality with tests
* [ ] Add policy to define the number of necessary positions
* [ ] Add policy to define the attribute from the user store as preset
* [ ] Add policy to read value dynamically

**Comment by cornelinux** [comment]
# Enroll Policies:

This is only to preset the value in the UI from the user attribute

* scope: webui
* action: preset_index_secret_with_attribute = attribute

Then there is a policy to force the attribute:

* scope: user / admin
* action: force_indexed_secret_with_attribute = attribute

This way the admin (or the user) can only "trigger" the enrollment, but privacyIDEA will fill the otpkey and ignore any user input.

**Comment by cornelinux** [comment]
I am missing the preset functionality. This is a bit tricky, since a new request has to be done, when a user is chosen. This is probably similar to the SMS token, that shows the available mobile numbers of a user.

It is here:

https://github.com/privacyidea/privacyidea/blob/master/privacyidea/static/components/token/controllers/tokenControllers.js#L349

But the actual attribute that is returned might be different for *each* user!
