### ISSUE TITLE
Add script to enroll PIV Yubikey

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#2054]
With the tool ``ykman piv`` we can automate the key generation on the Yubikey and the gerneration of a CSR.
The CSR can be sent to ``/token/init`` for a certificate request.

See https://privacyidea.readthedocs.io/en/latest/modules/lib/tokentypes/certificate.html#privacyidea.lib.tokens.certificatetoken.CertificateTokenClass

In combination with #2052 these certificates can then be used to login via ssh to linux machines.

# TODO

* [x] Add basic script to endpoint /token/init
* [x] /token/init needs a new paramter for the attestation certificate (or attestation certificate chain) for tokentpye "certificate"
* [x] Use attestation certificate to verify, that the priv key was generated on the yubikey.

**Comment by cornelinux** [comment]
I am moving this to prio high, since I would also like this for ourselves.

**Comment by cornelinux** [comment]
* [ ] concept of standalone script
* [ ] prototype

**Comment by cornelinux** [comment]
Please put this script into privacyideaadm repo.

**Comment by plettich** [comment]
The standalone script is added to the privacyidea-admin tool in https://github.com/privacyidea/privacyideaadm/pull/54

**Comment by cornelinux** [comment]
Since this is done in #2465 we close this isse.
