### ISSUE TITLE
Basic dashboard

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#2177]
As a first step to idea we can add a static dashboard. This is to get some experience from users how they like the dashboard and what they are missing.

The complete dashboard topic is discussed in #951 

Possible contents for the dashboard:

* Number of tokens / tokentype or tokenkind, assigned tokens, unassigned tokens
* Runtime of license
   * Number of users with tokens
* Number of active / inactive policies -> link
* Number of active / inactive event handlers -> link
* Last failed auth from audit - like last 5 failed /validate/check
* Last system changes by admins. (Like policy changes, resolver changes, realm changes)
* Blog posts via RSS (configurable)
* SSL validity check #1896
* Link to web form for dashboard feedback

# Todos

* [x] UI Mock up
* [x] Determine the **bootstrap elements** to be used
* [x] Determine the **endpoints** we need to gather the information. We try to use existing endpoints. This way also admins will only see information they are allowed to and we do not need new policies for viewing the dashboard.
* [x] Implement the **missing endpoints** (or only one /dashboad endpoint?
   * [x] Add tests for tokeninfo of GET /token
* [x] Stick togeather the bootstrap elements and the endpoints
   * [x] Tokens
   * [x] Authentications
   * [x] Administration
   * [x] Policies
   * [x] Events
   * [x] Subscriptions
* [x] Add WebUI policy to define, if an administrator should see the dashboard or not.

**Comment by cornelinux** [comment]
# Todos

* [ ] UI Mock up
* [ ] ...

**Comment by cornelinux** [comment]
![Dashboard-draft](https://user-images.githubusercontent.com/1908620/81716552-caa53600-9479-11ea-992e-163dc4539022.png)

**Comment by cornelinux** [comment]
# Bootstrap elements to use

from a design perstective of the current UI, we have always white elemts on a grey background with a headline in the white box. I would go for the same simple design here:

![image](https://user-images.githubusercontent.com/1908620/81919873-ae6bdb00-95d8-11ea-935e-0fcb80ca405b.png)

~~~~html
<div class="well">
   <div class="row">  <-- upper row -->
       <div ui-view class="col-lg-4 slide panel">
             <h3 translate>Title A</h3>
              ... content ...
       </div>
       <div ui-view class="col-lg-4 slide panel">
             <h3 translate>Title B</h3>
              ... content ...
       </div>
       <div ui-view class="col-lg-4 slide panel">
             <h3 translate>Title C</h3>
              ... content ...
       </div>
   </div>
   <div class="row">
       ... lower row ...
   </div>
</div>
~~~~

**Comment by cornelinux** [comment]
# Necessary endpoints

## Tokens

We would like to view the number of software tokens and hardware tokens.
The information is *tokenkind* which is stored in the tokeninfo. 
But currently the ``GET /token/`` endpoint does not allow to query tokens by tokeninfo.

So we need to somehow provide the possibility to query tokens by tokeninfo.
