### ISSUE TITLE
Clean up http proxy configuration

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#2206]
Several components need to talk to services via HTTP like
* HTTP SMS Gateway
* Firebase Gateway
* Yubico Token Config
* Fetching of policy templates

We could have a centrally defined HTTP/HTTPS proxy, that is used for all these tasks.
OR: 
We could centrally define HTTP/HTTPS proxies and select at each position which of the proxies we want to use (just as we do with all other servers/services.)

**Comment by cornelinux** [comment]
# Todos
* [x] Add proxy to firebase config
* [ ] No proxy for Yubico tokens
* [ ] No proxy for policy templates
* [ ] define central proxies
