### ISSUE TITLE
Dashboard v2

### ISSUE THREAD

**Issue by laclaro** [privacyidea/privacyidea#2484]
After the first version of the dashboard in privacyIDEA 3.4, a couple of ideas came up. This issue is to collect and discuss changes of the dashboard for the next round.

# Ideas to extend the dashboard

## Ideas with issues
- [ ] Search for users and token serials (#2458)
- [ ] Split Token numbers according to type (#2457)
- [x] Add column with the user to the authentications (#2475)
- [x] Display only info which an admin is allowed to see and prevent unprivileged requests (#2456)
- [ ] Split authentications by realm or client ip (and thereby by "authentication source") (#2483)
- [ ] Notification for new versions in the UI/Dashboard (#2560)

## Further ideas

- A piece of valuable information would be the general load of the system. Filter the audit log for the number of hourly requests during a day (and plot them with simple bars or a line).
- We should optimize the display. Because of the possibility to hide panels according to permissions, we should adjust the number of columns depending on the number of displayed panels.
- Number of rows in the audit log
- Size of the privacyIDEA log file on the hard disk.

# Types of information in the dashboard

## Admin Info
This information is mostly static and contains shortcut links to the respective sections in the WebUI.
- Shortcut links to policies and events.
- Info about the general health of the system 
  - Tokens, split by type
  - Subscriptions
  - Statistics about the number of requests during the week

## Helpdesk Info
Dynamic information which makes it easier for helpdesk users to identify users or tokens with problems
- User Search
- Token Serial Search
- Recent Authentications with clickable usernames
- Deactivated/expired tokens

**Comment by cornelinux** [comment]
> A piece of valuable information would be the general load of the system. Filter the audit log for the number of hourly requests during a day (and plot them with simple bars or a line).

One we had this idea, but we decided against it till now. This is why we have the event counters, to graph such things in other solutions like grafana.
The dashboard should not be a monitor to look at, since it will lock you out again. So there is no need in having monitoring graphs.
But thie components displayed in the dashboard should allow the admin to take quick actions!

> Number of rows in the audit log
> Size of the privacyIDEA log file on the hard disk.

I think all OS things are not the responsibility of privacyIDEA. Imagine a privacyIDEA setup with several nodes. What is the harddisk size.
Such OS data should be monitored by a normal monitoring tool.
I think this can be a good rule of thumb, that the dashboard should not do monitoring but always allow to do actions.

**Comment by laclaro** [comment]
I close this for now.
