### ISSUE TITLE
Add Microsoft CA Connector

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#2966]
Internal project to add Microsoft CA Connector.

# Todos

1st step

* [x] The CA worker returns all available CAs. Allow to choose the CA in the domain. This should be configured in the CA connector.
* [x] Mark broken certificate tokens in privacyIDEA. We could also delete such broken tokens directly after the rollout attempt.
* [x] Remove the caconnectortypes endpoint. In geneal this would make sense, but we also do not have an endpoint for tokentypes, resolvertypes. And I guess the ca connector types will change very seldomly. We might in the future put this in a general/central get types or get config endpoint.
* [x] Test with mock
* [x] Documentation
* [x] Fix `pi-manage ca create`
* [x] Check if we need to add code logic, since grpc needs Python > 3.6. However, Ubuntu 18.04 comes with Python 3.6.9.
* [x] Move `_conncet_to_server` to the constructor of the connector.

2nd step

* [ ] #3233
* [x] ~~Support enrollment on behalf of another user~~ This will be covered by the worker itself.

3rd step 

* [x] Mark the token as pending
* [x] Save the reply.requestID to the tokeninfo: https://github.com/privacyidea/privacyidea/blob/0e6dffcc0382e76a76ba23ee89c8bcff7914afb2/privacyidea/lib/tokens/certificatetoken.py#L448
* [x] ~~Add possibility to ask/query for pending requests~~
* [ ] #3232
  * [ ] GET /token/ could just-in-time ask the CA if, a "pending" "certificate" has been issued and update in accordingly. The necessary information (which CA, requestID) would be availble in order to query th CA. (Or put it in ttype endpoint?)
    * [ ] `GetCRStatus`.
    * [ ] `GetCertificate`
  * [ ] What should happen with a certificate token, if the **pending** request on the CA was denied. The rollout_state is not **FAILED** or **BROKEN**. It is rather **DENIED**.

**Comment by elouin** [comment]
branch created with initial code: https://github.com/privacyidea/privacyidea/tree/2966/add_micrsoft_ca_connector

**Comment by cornelinux** [comment]
# Broken certificate requests.

This can happen, e.g. if you try to enroll a `SubCA` cert to a user. 
It results in a Server 500 Error. Usually somewhere around here:
https://github.com/privacyidea/privacyidea/blob/47a374d3bc0a1fdcb959032227a1236e7abf20e3/privacyidea/lib/tokens/certificatetoken.py#L436

**Comment by cornelinux** [comment]
@plettich How can we run certain tests/test files only starting from a certain version?

**Comment by cornelinux** [comment]
Move the remaining tasks to own issues.
Closing this one.
