### ISSUE TITLE
Add webhook as event handler

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#2978]
We could add the possibility to call a webhook as an event handler.

* POST / GET
* URL
* content type
* data
* parameter

However, this seems a bit much in the UI, as a first step we could provide a script, that actually performs this web call via `requests`.

# Todos

* [x] documentation
* [x] ~~Make it configurable: wait for a response or not (see the script handler, that can run the script in the background / early return / fire and forget)~~
* [x] How should we use the response: use HTTP Response code or more? (see the SMS handler, that uses the response)
* [x] data field

Next Steps

* [ ] #3178

possible extension
- [x] ~~configurable timeout time~~

Use Case: When logging in in the morning automatically turn on your smarthome coffee maker.

**Comment by romanstech** [comment]
Just an example of such functionality in Netbox system.
<img width="631" alt="Webhook_example" src="https://user-images.githubusercontent.com/63143280/151332853-967cf51f-45d2-41eb-b756-ad443936f6ad.png">

**Comment by cornelinux** [comment]
We currently assume, that the server processes the web hook immediately, i.e. we get a quick response.
So we postpone processing a webhook in the background.
