### ISSUE TITLE
Multi-Challenge: Allow token enrollment during /validate/check

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#2993]
We have the possibility to add mechanism in a multi-challenge response communication during `/validate/check`.

Currently we do this for [changing pins](https://github.com/privacyidea/privacyidea/blob/28f138522618915950769a0fe196720f3b417393/privacyidea/lib/challengeresponsedecorators.py#L76) and for [resyncing tokens](https://github.com/privacyidea/privacyidea/blob/28f138522618915950769a0fe196720f3b417393/privacyidea/lib/challengeresponsedecorators.py#L169).

The goal is, to also allow enrollment of tokens during /validate/check.
To do so, we need to be able to provide an image in the challenge.
This image would be the QR code to enroll e.g. an HOTP or TOTP token.

We could also enroll a token by asking the user for an email-address or phone number (SMS token).

A possible workflow would then be:

1. User authenticates with an enrollment specific token like a `registration` token.
2. Challenge Response kicks in and displays the QR code to the user.
3. The user scans the QR code and responds with the OTP value.

# Challenge Layout

The challenge can consist of:

~~~~JSON
    "detail": {
        "client_mode": "interactive",
        "message": "please enter otp: ",
        "image": dataimage,
        "messages": [
            "Please scan the QR code and enter the OTP value: "
        ],
        "multi_challenge": [
            {
                "client_mode": "interactive",
                "message": "please scan the QR code and enter the OTP value: ",
                "serial": "OATH00923606",
                "transaction_id": "11164201982521632037",
                "type": "hotp"
            }
        ],
        "serial": "OATH00923606",
        "threadid": 140406862636800,
        "transaction_id": "11164201982521632037",
        "transaction_ids": [
            "11164201982521632037"
        ],
        "type": "hotp"
    },
 ~~~~

## Polling

Do we need information, where to poll?

If we would enroll a push-token, usually privacyIDEA polls to check, when the enrollment is done.
In this case we should send the generic information to the client: "please press enter".

We could however try to tell the client to only display the QR Code and not an input field. This way we could also support the enrollment of Push-Tokens.

## Cryptographic Challenges

TODO: Where would the cryptographic challenges be sent? Can this be generic or would it always be token type specific?

Enrolling Smardcards could roughly be impossible. Enrolling WebAuthn Tokens would require a lot of javascript logic in the client components.

## Client mode

The client modes are described here https://privacyidea.readthedocs.io/en/latest/tokens/authentication_modes.html and currently: interactive, u2f, webauth, poll.
Client modes are defined here: https://github.com/privacyidea/privacyidea/blob/db71956c5670a587690923d53fc059934b25c04b/privacyidea/lib/tokenclass.py#L137

# Conditions and Scenarios

What would be the conditions *when* this new token would actually be enrolled? 

This somehow also links very closely to #2956.

* [x] A user might have no token at all (authenticating via passthru) and is supposed to enroll his first token
* [x] A user has a registrationcode and will enroll his first token

# Alternatives

~~We could also enroll a token with a pre-event handler - we can already do this with SMS or Email tokens.  In case of HOTP or TOTP the QR code would need to be displayed. However, we would still end up in a challenge response, so this approach seems more sensible.~~

# Implementation

## Policy

The policy would be:

* scope: auth
* action: enroll_token_via_multichallenge=<tokentype>. # This can only take *one* tokentype, since it must be clear, which token would be enrolled. I think at the first step possible candidates are HOTP and TOTP -> `enroll_token_via_multichallenge=HOTP`. We could even use a dropdown for the allowed tokentypes.

What is currently not clear, if and how a PIN should be set for the token?

We could add an additional boolean policy like `enroll_token_via_multichallenge_with_pin`, or we could require to set a weird value in `enroll_token_via_mujltichallenge`. I think the second policy might be clearer.

### How should privacyIDEA know, that it does not need to enroll anymore?

One possibility: If the policy is set to `enroll_token_via_multichallenge=HOTP`, then enrollment does not take place anymore, if the user already *has* an HOTP token.

Other possibility: We need conditions, when to enroll and when not to enroll anymore. The condition could be some kind of "authenticated in way X: auth with passtrhu/ regcode...".

## Enrollable token types

The following token types could ab available with two or three steps.

* [x] HOTP  (scan QR code; enter OTP)
* [x] TOTP (scan QR code; enter OTP)
* [x] PUSH (scan QR code; hit enter; confirm on Device)
* [x] Email (enter Email-Address; then the OTP value sent)
* [x] SMS (enter Phone number; then the OTP value sent)

The tokenclass should define, if this tokentype `is multichallenge enrollable`. The token specific enrollment logic should be contained in the tokenclass code. This way, the decorator would only contain the glue code.

If we add another tokentype to be multichallenge enrollable later, then we can simply enhance the class.

The policy definition can iterate over the tokeclasses and generate the list of multichallenge enrollable tokentypes.

## Decorator

~~The decorator would be implemented as another challengeresponsedecorator [here](https://github.com/privacyidea/privacyidea/blob/28f138522618915950769a0fe196720f3b417393/privacyidea/lib/challengeresponsedecorators.py#L76).~~

This does not work out, since this location is only hit, if the user authenticated with a token.
If the user authenticates via passthru or PassOnNoToken, this will not work.
Thus we need to create post-decorator for /validate/check.

The decorator would be glue logic. 
* It fetches the policy and determines, which tokentype to enroll. (policy)
* It then checks, if the user has such a tokentype (condition)
* If not, it then passes the code logic to the corresponding tokenclass. (class method)

# Todos

* [x] Implement multichallenge-enrollable list creator
* [x] implement policy
* [x] implement decorator glue logic
  * [x] Add `multichallenge in response`
* [x] implement specific tokenlogic
  * [x] HOTP
  * [x] TOTP
  * [ ] PUSH
  * [x] Email
  * [x] SMS
* [x] tests
* [x] docs. 

**Docs**

Since it is implemented as policy, we can only enroll **one** token type. It is not possible to enroll an HOTP, then a TOTP and then a PUSH-Token during the authentication process. This might be possible, when we have more generic conditions one day.

A PIN can currently not be set during enrollment.

max_token policies are not checked.

**Additional Notes**

This can be related to #1511

# Test layout

## Enroll a HOTP token

User has no token, authenticates via passthru, enrolls an HOTP token.

1. Policy scope:auth, action:enroll_via_multichallenge=hotp
2. /validate/check as passthru
3. The decorator needs to 
   * modify the result->value=True to False.
   * modify this to a challenge, thus create a transaction_id, modify result->auth, add the image of the QR code, clientmode interactive, message_text...
4. The user then scans the QR code and enters the OTP value. The plugin sends a /validate/check again with the OTP value and the transaction_id. This way we can handle this as a quite normal response to a challenge. In theory this does not need to be handled by the decorator!
6. Finally the server needs to return a result->auth=SUCCESS.

## Enroll an Email token

User has not token, authenticates via passthru, is asked for his email address, an email needs to be sent to him, enters the OTP.

1. Policy scope:auth, action:enroll_via_multichallenge=email
2. /validate/check as passthru
3. the decorator needs to:
   * modify the result->value
   * create an email token without email address
   * create a CR with transaction_id (client mode: interactive)
4. Ask the user for the email address
5. Run a /validate/check with *transaction_id and email address*
6. Finalize the token with email address and create the real challenge and send email to user
7. ask for OTP
8. Run /validate/check with next *transaction_id and OTP value*

## Enroll a PUSH token

1. Policy scope:auth, action: enroll_via_multichallge=email
2. /validate/check passthru
3. The decorator needs to:
    * modify the result->value
    * create a push token first enrollment step
    * send QR code as image (client mode: poll)
    * create a challenge/tranaction_id for the enrollemt process
4. The client will display no input field, only the Enrollment QR Code
5. the smartphone will finish the enrollement -> the above transaction_(id) needs to be finalized
6. client will poll the ready enrollment transaction
7. client sends /validate/check with transaction_id (of the enrollment)
8. Server needs to create an authentication C/R (just as we use to do)
9. The server will update

**Comment by cornelinux** [comment]
# Implementation

## Policy

The policy would be:

* scope: auth
* action: enroll_token_via_validate=<tokentype>. # This can only take *one* tokentype, since it must be clear, which token would be enrolled. I think at the first step possible candidates are HOTP and TOTP -> `enroll_token_via_validate=HOTP`. We could even use a dropdown for the allowed tokentypes.

What is currently not clear, if and how a PIN should be set for the token?

We could add an additional boolean policy like `enroll_token_via_validate_with_pin`, or we could require to set a weird value in `enroll_token_via_validate`. I think the second policy might be clearer.

## Decorator

The decorator would be implemented as another challengeresponsedecorator [here](https://github.com/privacyidea/privacyidea/blob/28f138522618915950769a0fe196720f3b417393/privacyidea/lib/challengeresponsedecorators.py#L76).
