### ISSUE TITLE
App token (Application specific password)

### ISSUE THREAD

**Issue by katgirl** [privacyidea/privacyidea#3260]
App tokens would allow devices that do not support two-step confirmation to log in. 

Users can create an app token that has a pre-configured character length and complexity. 
They only need to enter the token once and therefore do not need to remember it. The app token can then be used to switch email clients, for example, to multifactor authorization.

In webmail, the user can then use password and his token (e.g. YubiKey, OTP or TAN). For the e-mail client on the cell phone, he can create an app token and thus continue to use the PUSH function.

This could provide additional security for the e-mail account and reduce the amount of SPAM sent.

-- edit by @cornelinux  --

# Implemenation consideration

We could use pw-tokens with conditions like IP addresses and HTTP-header `User-Agents`. However, this would probably be overkill. So it might make sense to add these aspects directly into the token.

We might assume, that one user usually would only have two or three of such tokens, since a user would usually only need to circumvent two or three services from mfa.

So the token could be derived from a [PasswordTokenClass](https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/tokens/passwordtoken.py#L43).

It could add the following attributes:

* `client` attribute to match. As IP address - not that nice
* `service groups` / `service identifier` aka `machine group` as in #3300 and #3246. Such machine groups should be defined, to avoid mistake-by-typo. This service group would be transferred in an additional parameter like "service" to /validate/check 
* `user-agent` to match, as taken from the http header field `User-Agent` if available. However, such services should be defined to avoid mistake-by-typo.

If the attributes/conditions can not be verified, this token should not be usable.

Depending on these attributes the token as to be added or removed from the token list in `check_token_list`.
*Hm, We might add a hook to add a token to this list in the base tokenclass.*

## Pass the Identifier

The token checks for a `service_id` in the /validate/check or trigger-challenge request.
Either application plugins could do this on their own or privacyIDEA can enrich the request with the `service_id` using the Pre-Event Handler `RequestMangler` depending on e.g. the client IP or the realm.

Now the `service_id` gets passed in the `options` parameter to `check_user_pass` (https://github.com/privacyidea/privacyidea/blob/49f64d01b2bffeacabeac721a405d46d9a62725d/privacyidea/api/validate.py#L406)
and finally to `check_token_list`
(https://github.com/privacyidea/privacyidea/blob/041972d21b3154721ff0c694d76902dd99da1d61/privacyidea/lib/token.py#L2058).

At the beginning of check_token_list here (https://github.com/privacyidea/privacyidea/blob/041972d21b3154721ff0c694d76902dd99da1d61/privacyidea/lib/token.py#L2193) we reduce the list of tokens. We can add another tokenclass hook, that uses the options to check, if a token should be used for authentication in this case and thus remove the application specific token if the service_id does not match.

# Todos

* [x] documentation, done in 2c41c079
* [x] Implement passing service_id and tokenclass hook `use_for_authentication(options)`. Done in e9bde1df
* [x] tests, done in 48b9ebe7
* [x] Implement tokenclass, done in 48b9ebe7
* [ ] #3533
* [ ] ~~policies for token (which one?)~~
* [x] UI, done in 44a05a62

**Comment by cornelinux** [comment]
It is not quite clear, what you want to achieve.

So you are looking for a new tokentype that provides a static password for authenticating at certain applications? To implement application specific passwords?

**Comment by stephanhendl** [comment]
Well, we've a similar problem. We authenticate Nextcloud-24.x against ADFS and use the privacyIDEA-ADFS-plugin for the second factor. This works perfectly for webbrowser and sync-clients because they open a webbrowser window where one can input username/password as well as OTP during the authentication process. 

The calendar app on iOS (and I assume on Android as well) cannot deal with that and fails. When one uses the 2FA solution within Nextcloud one can create app-passwords which bypass the 2nd factor. 

Unfortunately I've found a solution for using the calendar app in Nextcloud via ADFS/privacyIDEA. Maybe it's more a Nextcloud problem than a privacyIDEA problem...

**Comment by katgirl** [comment]
just as @stephanhendl has written. Let's find a simple way to provide a central way for certain "client" applications (delimited by policy) to allow users to continue using them with simple credentials in addition to the web-based mfa. In our case Thunderbird or Outlook.

**Comment by cornelinux** [comment]
Maybe we simply need to make the `pw` token available in the UI.

 http --verify no POST https://localhost/token/init type=pw genkey=1 authorization:$TOK

**Comment by cornelinux** [comment]
The password token could be connected with a hostgroup #285.
Just like an SSH key or offline OTP would send information about the host identifier.
Also compare https://community.privacyidea.org/t/authentication-via-userstore-for-linux-unix-systems-repost/2827

**Comment by cornelinux** [comment]
> Let's find a simple way to provide a central way

@katgirl Do you have a suggestion/idea how a user should manage an endless number of hostnames-and-passwords or applications-and-passwords?

So one part of your basic request was that a password gets generated for the user, since the user would only enter this once. Can you elaborate on this? How could this happen/ how could the workflow look like?

**Comment by katgirl** [comment]
The token should be configurable like all tokens and should also be able to be displayed via the token list. It should also be possible to set a policy for this type.
E.g. that it can only be used from the IP address of the mail server, but not from the IdP (SSO service) or VPN service. That there may be a maximum of three tokens of this token type, what length the token should have, what characters are allowed, etc.

In general, the user should be able to roll out this token type just like the TAN token or the TOTP token. We also need this via the REST API. Also nice would be to be able to do an event annually that informs the user of the possession of such tokens (this would not necessarily be the first requirement, but might be nice later on).

The procedure I would imagine is that the user rolls out a new "APP token" and instead of that as with the TAN list or the TOTP token a "password" is generated (on the rules of the policy). This is then displayed directly to the user just like the tokens mentioned above. He can then copy this into his "application" and use it (see: https://wiki.ubuntuusers.de/pwgen/). 
I would not see any device management or similar here. In my view, this should be regulated organizationally or via policy (restriction to certain IP addresses/services).

**Comment by cornelinux** [comment]
> The token should be configurable like all tokens and should also be able to be displayed via the token list. It should also be possible to set a policy for this type. E.g. that it can only be used from the IP address of the mail server, but not from the IdP (SSO service) or VPN service. That there may be a maximum of three tokens of this token type, what length the token should have, what characters are allowed, etc.

@katgirl thank you for your input. We will take this into account. However our duty is to deny specific user requests and create an abstraction so that it will work in many cases to avoid a code clots due to single specific featrue requests. privacyIDEA rocks, since we adhere to this concept.

**Comment by cornelinux** [comment]
> Well, we've a similar problem. We authenticate Nextcloud-24.x against ADFS and use the privacyIDEA-ADFS-plugin for the second factor. This works perfectly for webbrowser and sync-clients because they open a webbrowser window where one can input username/password as well as OTP during the authentication process.
> 
> The calendar app on iOS (and I assume on Android as well) cannot deal with that and fails. When one uses the 2FA solution within Nextcloud one can create app-passwords which bypass the 2nd factor.
> 
> Unfortunately I've found a solution for using the calendar app in Nextcloud via ADFS/privacyIDEA. Maybe it's more a Nextcloud problem than a privacyIDEA problem...

So it is NOT possible in Nextcloud to use app-passwords, if the authentication for nextcloud is switched to SAML?

**Comment by cornelinux** [comment]
> just as @stephanhendl has written. Let's find a simple way to provide a central way for certain "client" applications (delimited by policy) to allow users to continue using them with simple credentials in addition to the web-based mfa. In our case Thunderbird or Outlook.

@katgirl  "Thunderbird" and "Outlook" actually do not do authentication. Thunderbird and Outlook send passwords to the Mailserver and this mailserver verifies the passwords. I.e. your mailserver would need to communicate to privacyIDEA and use app-passwords. Which mailserver and which authentication protocol are you using?

**Comment by katgirl** [comment]
We use LDAP for logging in to the mail server (Dovecot/Postfix). 
The webmailer (horde) itself does not log in against LDAP, but passes its credentials directly to the Dovecot. So we only have to change the source to the 2FA-LDAP proxy. After that the login would run against PrivacyIDEA.
With the webmailer, users should log in via password + token (instead of just password as before). However, those who use a mail client (Thunderbird, Outlook, ...) should have the option of logging in not with password + token for each call, but with a permanently valid APP token. 
This is particularly interesting if you use the mail client on your smartphone and use the push notification there, e.g. to be notified by the monitoring in the event of faults.

Translated with www.DeepL.com/Translator (free version)

**Comment by cornelinux** [comment]
> We use LDAP for logging in to the mail server (Dovecot/Postfix).
> The webmailer (horde) itself does not log in against LDAP, but passes its credentials directly to the mail server. So we only have to change the source to the 2FA-LDAP proxy. After that the login would run against PrivacyIDEA.
> With the webmailer, users should log in via password + token (instead of just password as before). However, those who use a mail client (Thunderbird, Outlook, ...) should have the option of logging in not with password + token for each call, but with a permanently valid APP token.
> This is particularly interesting if you use the mail client on your smartphone and use the push notification there, e.g. to be notified by the monitoring in the event of faults.

Thanks. Still your challenge would be to distinguish on the ldap/ldap-proxy if the request originates from horde or from a mail client.

**Comment by stephanhendl** [comment]
> > Well, we've a similar problem. We authenticate Nextcloud-24.x against ADFS and use the privacyIDEA-ADFS-plugin for the second factor. This works perfectly for webbrowser and sync-clients because they open a webbrowser window where one can input username/password as well as OTP during the authentication process.
> > The calendar app on iOS (and I assume on Android as well) cannot deal with that and fails. When one uses the 2FA solution within Nextcloud one can create app-passwords which bypass the 2nd factor.
> > Unfortunately I've found a solution for using the calendar app in Nextcloud via ADFS/privacyIDEA. Maybe it's more a Nextcloud problem than a privacyIDEA problem...
> 
> @stephanhendl So it is NOT possible in Nextcloud to use app-passwords, if the authentication for nextcloud is switched to SAML?

Well, we tried it some days again and could solve the problem so that we can use app-passwords although we use 2FA with ADFS/SAML.
