### ISSUE TITLE
New Authentication flow, login without username

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#3526]
There are scenarios, where a login might not require a username. This can be true for WebAuthn but also for mechanisms like a Smartphone app, that simply scans a QR code and sends the response including the username and the serial.

Currently we have the following authentication workflows:
-- missing --
Also see the authentication mode and clients modes.
https://privacyidea.readthedocs.io/en/master/tokens/authentication_modes.html

We would have to design a new workflow and authentication mode that basically works like this:

1. privacyIDEA is told, to prepare for authentication. Hm, could this connected to pre-authentication? #3033 
2. privacyIDEA then creates a challenge, without a username and a serial. I.e. look at the challenge table: 
   https://github.com/privacyidea/privacyidea/blob/master/privacyidea/models.py#L1387
   So from a DB perspective we actually can create challenges without a serial
3. privacyIDEA sends the challenge and the transaction_id
3. The clients sends back to the privacyIDEA server:
     - username
     - optional: serial (this will not be possible with webauthn)
     - additional optional data
     - response to the challenge
     - transaction_id
4. Only now can privacyIDEA use the username and/or additional data to identify the user and the token and verify the challenge via the transaction_id.

Possible scenarios are:

* Webauthn with out username #3336 
* Use Authenticator App like datev unternehmen online.

## Implementation steps

* [ ] Design workflow
* [ ] Check the possibility to create "detached" challenges, that are not connected to a token. We need a generic "create_challenge" function, since currently this is always done in a token object.
* [ ] check and enhance the `check_challenge_response` method to check for detailed challenges.
* [ ] Implement token specific behavious for webauthn and DUO.

**Comment by melanger** [comment]
@cornelinux Hello, I am working on passwordless authentication and I would like to extend privacyIDEA to support usernameless authentication. Currently, it is possible to sign in using a passkey but only after entering a username.

Is there any work in progress for this? May I start working on a PR and discuss with you? My idea is the same, create a new endpoint for detached challenges and modify the verification endpoint to accept them, then alter the WebAuthn token to be compatible.
