### ISSUE TITLE
Declined push requests

### ISSUE THREAD

**Issue by nilsbehlen** [privacyidea/privacyidea#3599]
In the upcoming version of our app 4.1.1, declined push requests are communicated to privacyidea.
Possibilities to use that information:

- Audit log to easily see if this occurs often
- Eventhandler?
- Should an application that is using that push token for authentication cancel the authentication? The info has from /validate/polltransaction, which currently only has a bool: true->accepted, false->not yet accepted.

**Comment by nilsbehlen** [comment]
I would prefer to change/replace the bool to/with a string and keep the HTTP 200 code, instead of changing the HTTP code.
For transitioning in versions, we could keep the bool and add a string that has more options.

**Comment by jona-samuel** [comment]
We will have to change the behaviour of the push token. We have to add the info that the request is declined to the challenge, instead of deleting the challenge, for sending different results if the challenge is declined and the challenge is not answered.
For backward compatibility, we keep the boolean and a new field with the extra information (like validate/check).

**ToDo**

- [ ] modify the challenge (challenge no longer will be deleted by declining)
- [ ] add a field to the result with info for "accept", "declined", "on hold" or "challenge not found"
- [ ] add the info to the audit log
