### ISSUE TITLE
Push fatigue mitigation

### ISSUE THREAD

**Issue by nilsbehlen** [privacyidea/privacyidea#3632]
Issue from the app with vague ideas: https://github.com/privacyidea/pi-authenticator/issues/289
Original Text:
If an attacker can trigger push notifications for a user, the static password is probably already compromised. In that case, it is not sufficient to just suppress the push notifications - the admin has to take action. However, it should be up to the admin what will be done.

General question:
How can we transfer the information of an unauthorized login attempt from the phone to privacyIDEA?

We could make the push buttons somewhat configurable:
- Optionally include a third button to indicate that the push request was not triggered by the owner of the phone -> what kind of request will be made?
- Texts

See: https://github.com/privacyidea/privacyidea/wiki/concept%3A-PushToken#decline
- We could also make use of "decline".

# Concept

We could use the "decline" information to allow the admin to trigger some notification.

A user receives a push notification. Why would he decline this message if it was not him, who triggered the login process. We could have a policy or an event handler, that the admin can set up to create such notification.

"Dear helpdesk team, please take care, since there are push notifications, that have beed declined by the user".

Maybe this could simple be a **condition** in an event handler?

We would then need to add an event definition at the endpoint `/ttype/<type>` here:
https://github.com/privacyidea/privacyidea/blob/9153e57f8830737661ca2287a1f8d28bf617652d/privacyidea/api/ttype.py#L87

We would also add more action at the declining of the challenge here:
https://github.com/privacyidea/privacyidea/blob/6e80ba271ab55bcd4f67f91207d8a7f8d8628d7a/privacyidea/lib/tokens/pushtoken.py#L641

The request in question would be

~~~
/ttype/push
serial
challenge
signature
decline=1
~~~
By the serial we would identify the token and thus the owner, e.g. to notifiy the owner or to deactivate the token.
conditions for endpoint /ttype/push would be: option decline=1.

## Todos

* [x] Add event decorator
* [x] Add token event handler action "increase tokeninfo"
* [x] Eventhandler needs additional condition:
        * ~~Either: for http parameter "decline=1" (could this done generic). Could work in *pre* and *post* event handling.~~
        * Alternative: Fitler in the *postevent* for the challenge state "declined", since this is written to the Challenge-Table. (Could also be a generic challenge state) Store it in the session.
* [x] Test: handler-action: increase_tokeninfo
* [x] Test: push-token: setting the challenge session to `challenge_declined`.
* [x] Test: Handler conditions `challenge_declined` and `expired`.
* [x] Docs
