### ISSUE TITLE
Do not request 2FA for a certain time period

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#3708]
**Is your feature request related to a problem? Please describe.**

Users are lazy and not security aware and always claim, that they do not want to enter their second factor.
Only once a week. Only twice a year. :-/

**Describe the solution you'd like**

During a normal authentication privacyIDEA can create a signed identifier. This is sent back and the web application privacyidea plugin saves this as a cookie.
privacyIDEA server can decide on policies in is contained in this identifier and under which condition it will generate such.
The identifier contains the current timestep - not the expeiration date!

privacyIDEA server also saves this identifier in a new database table with this user.

In the next authentication request, the privacyidea plugin will send this cookie in the pre-authentication phase.

The privacyIDEA server can verify this identifier and check in its policies if such an identifier is still valid depending on policies. This way the server can change the "validity period" of such already issued identifier via policies.

If the identifier is still valid, the privacyIDEA server returns to the privacyidea plugin in the pre-authentication request, that no authentication is necessary for this user.

**Describe alternatives you've considered**

Ignore the requests.

**Additional context**

The cookie is stored in the browser. The problem is, that a browser could be used by different users. E.g. an IT admin could use it as administrator and as normal user. 
So we need to be able to store several such cookies in the browser.
Maybe we need to add the user name to the name of the cookie.
Each privacyIDEA plugin would have it's own named cookie.

# Top level requirements and scenarios

* [ ] The validity period of an issued identifier can be changed by a policy on the server
* [ ] Serveral users must be able to use the same browser context

# Implementation TBD

*Cover the following aspects:*

## Database

Describe the database table that will be added. Define the `name` of the table and the `names of the columns`.

Define, if you need to add a DB migration script.

## Library and API

Describe what needs to be implemented, preferably also in which files.

Use example code of what you plan to implement:

~~~~Python
new_feature = [ x.name for x in some_return_values if x.id > 0 ]
~~~~

# TODOs

*In the TODO section you can add all steps that need to be implemented*

**USE CHECKLISTS, THESE WILL BE VISIBLE AS TASKS!**

* [ ] add DB table `name` in `models.py`
* [ ] create above mentioned migration script.
* ~~[ ] there might be an aspect that is not relevant anymore~~
* [ ] e.g. Add util function to...
* [ ] e.g. add REST API...
* [ ] e.g. we need to add policy and implement it in e.g. `prepolicy`
  - scope: admin
  - action: new_action_name
  - ...    

Use further checkboxes for

* [ ] add documentation
* [ ] implement tests

**Comment by nilsbehlen** [comment]
I think people would want this SSO-like behavior in privacyidea generally, shared across all logins (plugins) and not per plugin.

**Comment by nilsbehlen** [comment]
here is a pretty interesting use case: https://github.com/privacyidea/privacyidea-credential-provider/issues/131
