### ISSUE TITLE
node specific realms

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#3758]
**Is your feature request related to a problem? Please describe.**

In redundant setups with node in different geo-locations it can be useful to have slightly different configurations.
E.g. the priority of resolvers in a realm could be in a different order for different nodes.

We should find a way to allow some kind of node specific  configuration.

# Requirements

There are different scenarios that could result in the same requirement.

**Req1)** (necessary)

The different nodes use the same AD but should use different domain controllers due to the geo location.

"REALM A" on node 1 (Geolocation A):  Res A (Geolocation A), Res B (Geoloation B)

"REALM A" on node 2 (Geolocation B): Res B (Geolocation B), Res A (Geolocation A)

This would simply result in a different ordering. This means, there is one Realm that contains all users everywhere. Only users usually located in Geolocation A are resolved quicker in Geolocation A - users from Geoloc B will still be resolved in Geoloc A, but simply a bit slower.

This case works, if a user usually authenticates in his default Geoloc.

**Req2)**  (This is a generalization of Req1)

The different nodes could use different users, which originate even maybe from different LDAPs.

"REALM A" on node 1: Res A, Res B

"REALM A" on node2: Res B, Res C, Res D
This could also be used, e.g. if you have an Admin-Realm, to define the Admin-Realm on a DMZ node to be empty (without any resolvers), thus again preventing admins from login.

# Implementation thoughts

## Questions
- should every *new* resolver->realm relation have a node attached?

### Database

For Req1 and Req2 we could add a node to the ResolverRealm definition like this:

~~~~Python
class ResolverRealm(TimestampMethodsMixin, db.Model):
    """
    This table stores which Resolver is located in which realm
    This is a N:M relation
    """
    __tablename__ = 'resolverrealm'
    id = db.Column(db.Integer, Sequence("resolverrealm_seq"), primary_key=True)
    resolver_id = db.Column(db.Integer, db.ForeignKey("resolver.id"))
    realm_id = db.Column(db.Integer, db.ForeignKey("realm.id"))
    # If there are several resolvers in a realm, the priority is used the
    # find a user first in a resolver with a higher priority (i.e. lower number)
    priority = db.Column(db.Integer)
    node_uuid = db.Columd(db.UUID, db.ForeignKey("pinode.uuid"))
    resolver = db.relationship(Resolver,
                               lazy="joined",
                               back_populates="realm_list")
    realm = db.relationship(Realm,
                            lazy="joined",
                            back_populates="resolver_list")
    __table_args__ = (db.UniqueConstraint('resolver_id',
                                          'realm_id',
                                          'node_uuid',
                                          name='rrix_2'),
                      {'mysql_row_format': 'DYNAMIC'})
~~~~

This way we can have the same `realm -> resolver` connections with different `node_uuid`s.
If no node-specific `realm->resolver` connection is required, the `node_uuid` is `null/None`.

#### adding a realm
- `set_realm()` gets a realm name and an optional list of dictionary with the resolver information:
  ~~~~Python
  resolvers = [
    {'name': 'resolver1',
     'priority': None,
     'node': None},
    {'name': 'resolver2',
     'priority': 1,
     'node': uuid1},
    {'name': 'resolver2'}
  ]
  ~~~~
  since the node is specifically bound to a resolver -> realm relation.

When we read/update the local config object, we add the resolvers to the realm. There we add the `node_id` to the resolver-dict. The result could thus contain multiple resolver entries with the same name. We would have to filter out the resolver based on the `node_id` when actually resolving a user.

### API

Add a new endpoint `/realm/<string:realm>/node/<string:nodeid>` which receives the node specific configuration in a list:
```JSON
[
  {
    "name": "resolver1",
    "priority": 1
  },
  {
    "name": "resolver2",
    "priority": 2
  }
]
```

### Node Name / ID

Currently the list of the nodes is stored in the pi.cfg. It might make sense to add the list of the nodes in the database, we could then also use `node_id` (See #3757).

privacyIDEA could read the `PI_NODE` from pi.cfg and write it to the database, thus creating a list nodes in the database.

The local node name would still be stored in the pi.cfg.

### UI

In the realm config we could have a matrix of resolvers per node added to a realm with the corresponding priority.

![nodes2](https://github.com/privacyidea/privacyidea/assets/1908620/8eac42aa-e6ae-4c22-a279-7a4d5d6dbfa5)

## TODO
- [x] implement library layer (get/set realms with/without nodes)
- [x] define and implement the API layer
- [x] UI
- [ ] documentation (including examples)
