### ISSUE TITLE
Add multiple choice for realms and resolvers in eventhandler

### ISSUE THREAD

**Issue by jona-samuel** [privacyidea/privacyidea#3793]
**Is your feature request related to a problem? Please describe.**

We use multi-choice for the token realm, token resolver and toke type, so we should use this here too. 

**Describe the solution you'd like**

We can change the type from str to multi for realm and resolver in evanthandler/base.py similar to tokenrealm

# Implementation

# TODOs

- [x] change the type of realm and resolver here: https://github.com/privacyidea/privacyidea/blob/0facb209610e6553cc1f420e1d65f454f85e3460/privacyidea/lib/eventhandler/base.py#L149
- [x] we have to change this: https://github.com/privacyidea/privacyidea/blob/0facb209610e6553cc1f420e1d65f454f85e3460/privacyidea/lib/eventhandler/base.py#L416
- [x] Test it
- [x] Check docu: https://github.com/privacyidea/privacyidea/blob/master/doc/eventhandler/index.rst#conditions
