### ISSUE TITLE
Add entries to the audit log

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#3856]
In the Audit log we should have the following entires:

* User Agent (that helps with identifying if this is an auth request from RADIUS or Keycloak or etc
* result->authentication: with the allowed values REJECT; SUCCESS; CHALLENGE

## Todos

* [x]  Add in models.py:

additional entries in audit_column_length:

                       "authentication": 12,
                       "user_agent": 20,
                       "user_agent_version": 20,

in the audit table.

    authentication = db.Column(db.Unicode(audit_column_length.get("authentication")))
    user_agent = db.Column(db.Unicode(audit_column_length.get("user_agent")))
    user_agent_version = db.Column(db.Unicode(audit_column_length.get("user_agent_version")))

* [x]  Also add the three columns in "available_audit_columns" in auditmodules/base.py

* [x] In the before_requests in auth.py, before_after.py, ttype.py, validate.py add in the audit_object.log():

                        "user_agent": request.user_agent.browser,
and the version.

* [x] In validate.py we need to add the result->authentication to the audit_object.log(). Done in 822fd3448

* [x] Adapt the UI.
  * [x] Make authenticationFilter etc work

**Comment by cornelinux** [comment]
* [ ]  Add in models.py:

additional entries in audit_column_length:

                       "authentication": 12,
                       "user_agent": 20,
                       "user_agent_version": 20,

in the audit table.

    authentication = db.Column(db.Unicode(audit_column_length.get("authentication")))
    user_agent = db.Column(db.Unicode(audit_column_length.get("user_agent")))
    user_agent_version = db.Column(db.Unicode(audit_column_length.get("user_agent_version")))

* [ ]  Also add the three columns in "available_audit_columns" in auditmodules/base.py

* [ ] In the before_requests in auth.py, before_after.py, ttype.py, validate.py add in the audit_object.log():

                        "user_agent": request.user_agent.browser,
and the version.

* [ ] In validate.py we need to add the result->authentication.

* [ ] Adapt the UI.
