### ISSUE TITLE
2 person login 

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#3897]
PUSH token that needs interaction with the user and the login page.

The scenario is, that one person sits in front of the login page and the other person is the owner of the 2nd factor.
The 1st person logs in. The 2nd person is required to contact the first person. A personal interaction is requested between the two persons - the PUSH token would allow a login without interaction.

This seems to be different from the push fatigue requirement in #3632 

Questions:
* Why not use SMS or Email? Speed? Costs?
* Why not use 4 eyes token?

cc: 174178
@nilsbehlen  I would like to discuss this in the next KESS.

**Discuss: Are we finde with a 33% chance of guessing?**

# Todos

* [x] We need to adapt this message: https://github.com/privacyidea/privacyidea/blob/6e80ba271ab55bcd4f67f91207d8a7f8d8628d7a/privacyidea/lib/tokens/pushtoken.py#L886
* [x] create challenge data, store challenge data, 
* [x] send callenge data to the smartphone, so that the smartphone can create the accordingly buttons. Enhance `_build_smartphone_data` https://github.com/privacyidea/privacyidea/blob/6e80ba271ab55bcd4f67f91207d8a7f8d8628d7a/privacyidea/lib/tokens/pushtoken.py#L903
* [x] enhance the processing of the smartphone response. https://github.com/privacyidea/privacyidea/blob/6e80ba271ab55bcd4f67f91207d8a7f8d8628d7a/privacyidea/lib/tokens/pushtoken.py#L614
How shoold we do this? We also could add the random number to the nonce and thus have it automagically in the response of the smartphone.
* [x] Add policy: scope:authentication, action:policy_require_presence. We could do this as a boolean checkbox or we could make configurable: number of possible numbers. length of possible numbers (which does not matter). We could also simply do "A", "B", "C". sind it is a 1/3 chance.
* [x] documentation
* [x] Add support for poll_only.
* [x] What should happen, if a user has several push tokens? We need to ensure, that a user, who has several push tokens and triggers several challenges, gets the same challenge `data`, since he most probably has the same transaction id entry in the challenge database? Done in 84d9aa270    (see #2323) 
* [x] If the user has several push tokens and one challenge received the wrong answer. Should the challenges of the other tokens be canceled? This would actually happen here: https://github.com/privacyidea/privacyidea/blob/84d9aa270c9d91e010ee2c4cb611c414947e5aa3/privacyidea/lib/tokens/pushtoken.py#L668

**Comment by cornelinux** [comment]
This would be related to #3632 or even would make it obsolete.

We could even, if the number is answered wrong, start to delete the challenge or block the token.

**Comment by frankmer** [comment]
@cornelinux 
Since the accepted/declined information is in the signed message body of the response, I would add the pressed number to the signed message and body as well.

```
signature =  {nonce}|{serial}[|decline][|number]
```
~~~~JSON
{ ...
   "decline": "0"
   "presence_answer":  "pressedNumber",
}
~~~~
