### ISSUE TITLE
Configurable possible answers of "require_presence"

### ISSUE THREAD

**Issue by frankmer** [privacyidea/privacyidea#4004]
Currently the App always shows "A", "B" and "C".

It would be better to make it configurable via policy and let the admin choose one of these options:

1. Letters from A-Z
2. Numbers from 01-99 
3. Custom defined list of options

The admin should also be able to configure how many options are shown on the phone

# TODOS

- [x] Implement policy "push_presence_options": The admin can choose between ALPHABETIC, NUMERIC or CUSTOM. ALPHABETIC is any uppercase letter (A-Z). NUMERIC is any number between 01 and 99.
- [x] Implement policy "push_presence_custom_options": The admin can enter any set of options. The options are separated by ":" e.g. "01:02:03:1A:1B:1C".
- [x] Implement policy "push_presence_num_options": The admin can enter any number. If the number is not possible, the number of options displayed is the closest possible number.
- [x] Edit the push token to use the policys: {num_options} randomly selected entries will be selectable in the authentication (no duplicates).
One of them is selected as the correct answer. To store the data, the selectable entries and the correct answer as the last entry are converted to a single string separated by a comma ",". The correct answer is always the last entry and the only duplicate.
Example: `"B,L,C,L"` The correct answer in this example is "L" and the choices are "B", "L", and "C".
We need to store the selectable entries to display the same challenge on different devices.
- [x] add documentation
- [x] implement test
