### ISSUE TITLE
Improve Readiness Endpoint to Accurately Reflect Dependency Status

### ISSUE THREAD

**Issue by henrik-falk** [privacyidea/privacyidea#4115]
**Is your feature request related to a problem? Please describe.**

Currently, when the readiness endpoint (/readyz) is called, the response does not accurately reflect the app's readiness status in all scenarios.

Checking if the app started using APP_READY is unnecessary, because to call the endpoint the app must already exist. But then the APP_READY is always true (unless it set to false again somewhere else). A more sophisticated solution may be helpful here.

The reason why APP_READY still exists was to provide a way for checking on further dependencies by toggling APP_READY before and after loading a dependency. Identifying all dependencies was not in the scope of #1115 but should be a task for the future and **released with the first official docker file** for privacyidea. 

What are you trying to achieve?

To check oh the health of the server with all its dependencies checked.

**Describe the solution you'd like**

When the readyz endpoint is called APP_READY in the app.config context will indicated the readiness. This flag should be toggled accordingly. 

*If sensible use a checklist to check, which requirements have been covered by your implementation!*

* [ ] We need to ensure that asynchronous dependencies don't result in incorrect readiness status

Use example code of what you plan to implement:

~~~~Python
app.config['APP_READY'] = False
# ... dependency is loading
app.config['APP_READY'] = True 
~~~~

# TODOs

- [ ] identify further dependencies
- [ ] toggle APP_READY accordingly
- [ ] implement proper solution to check if the app has started
- [ ] add documentation
- [ ] implement tests
